# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = ex1.o ex3.o "ex\ ASCII.o" exFor1.o $(RES)
LINKOBJ  = ex1.o ex3.o "ex ASCII.o" exFor1.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = Project1.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Project1.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "Project1.exe" $(LIBS)

ex1.o: ex1.c
	$(CC) -c ex1.c -o ex1.o $(CFLAGS)

ex3.o: ex3.c
	$(CC) -c ex3.c -o ex3.o $(CFLAGS)

"ex\ ASCII.o": ex\ ASCII.c
	$(CC) -c "ex ASCII.c" -o "ex ASCII.o" $(CFLAGS)

exFor1.o: exFor1.c
	$(CC) -c exFor1.c -o exFor1.o $(CFLAGS)
